<?php

namespace App\NCUO\EifBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatatypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatatypeRepository extends EntityRepository
{
    
    /**
     * Функция вывода списка типов данных с заданной сортировкой
     */
    
    public function getList() {
        return $this->getEntityManager()->createQuery('SELECT d FROM NCUOEifBundle:Datatype d ORDER BY d.sort_order ASC')->getResult();
    }
}
