<?php

namespace App\NCUO\EifBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileStatusRepository extends EntityRepository
{
    
    /**
     * Функция вывода списка статусов файлов с заданной сортировкой
     */
    
    public function getList() {
        return $this->getEntityManager()->createQuery('SELECT f FROM NCUOEifBundle:FileStatus f ORDER BY f.sort_order ASC')->getResult();
    }
}
