parameters:
    ############################################################################
    # Системные настройки                                                      #
    ############################################################################
    
#    ncuofoiv.path_from_app: "../web/"
    ncuooiv.path_img_foiv_schema: "/img/foiv/structure"
    ncuooiv.path_img_persons: "/img/foiv/persons"
    ncuooiv.path_img_upload: "/img/foiv/upload"
    
    ############################################################################
    # Типовые заголовки                                                        #
    ############################################################################

    title.view: "Просмотреть"
    title.create: "Создать"
    title.add: "Добавить"
    title.edit: "Редактировать"
    title.save: "Сохранить"
    title.delete: "Удалить"
    title.toList: "Вернуться к списку"
    title.addPerson: "Добавить персоналию"
    msg.created: "Запись успешно создана"
    msg.updated: "Данные успешно сохранены"
    msg.error.crt: "Ошибка сохранения данных! Запись не сохранена! "
    msg.error.upd: "Ошибка сохранения данных! "
    msg.error.notFound: "Элемент не найден!"
    msg.error.notFoundFoiv: "ФОИВ не найден или досуп к нему запрещен!"
