<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository
{
    
   /**
     * Функция вывода списка ролей по блокам
     */
    
    public function getDataByBlocks($start, $length) {
        $em = $this->getEntityManager();
        
        // Получаем общее кол-во строк
        $total_cnt = $em->createQuery(
            'SELECT COUNT(r) FROM NCUOPortalBundle:Role r'
        )
        ->getSingleScalarResult();
        
        // Получаем выборку строк в заданном диапазоне
        $data = $em->createQuery(
            'SELECT r FROM NCUOPortalBundle:Role r ORDER BY r.id ASC'
        )
        ->setFirstResult($start)
        ->setMaxResults($length)
        ->getResult();
        
        return array(
            'total_cnt' => $total_cnt,
            'data' => $data
        );
    }
}
