<?php

namespace App\NCUO\MapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MetaUnloadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaUnloadRepository extends EntityRepository
{
    
   /**
     * Функция вывода списка сервисов по блокам
     */
    
    public function getDataByBlocks($start, $length) {
        $em = $this->getEntityManager();
        
        // Получаем общее кол-во строк
        $total_cnt = $em->createQuery(
            'SELECT COUNT(meta) FROM NCUOMapBundle:MetaFunction meta'
        )
        ->getSingleScalarResult();
        
        // Получаем выборку строк в заданном диапазоне
        $data = $em->createQuery(
            'SELECT meta FROM NCUOMapBundle:MetaFunction meta ORDER BY meta.name ASC'
        )
        ->setFirstResult($start)
        ->setMaxResults($length)
        ->getResult();
        
        return array(
            'total_cnt' => $total_cnt,
            'data' => $data
        );
    }
    
}
