parameters:
    ############################################################################
    # Сообщения                                                                #
    ############################################################################
    
    ncuofunc.msg.service_error: "Ошибка взаимодействия с сервером!"
    ncuofunc.msg.exception: "При выполнении запроса произошла ошибка! В журнале событий сохранена запись с номером %s"
