<?php

namespace App\NCUO\OivBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class OivRepository extends EntityRepository
{
    
    /**
     * Функция получения кол-ва ФОИВ
     */
    
    public function getTotalCount() {
        return $this->getEntityManager()->createQuery('SELECT COUNT(f) FROM NCUOOivBundle:Oiv f')->getSingleScalarResult();
    }
    
    /**
     * Функция получения списка ФОИВ с кол-во дочерних ФОИВ и Инф. систем
     */
    
    public function getRoivSystemsCount() {
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare(
        '
            select
                  f.id as oiv_id
                , f.name as oiv_name
                , (select count(*) from eif_data2.dict_roiv r where r.oiv = f.id) as cnt_roiv
                , (select count(*) from eif_data2.dict_systems s where s.oiv = f.id) as cnt_systems
            from
                eif_data2.dict_oiv f
            order by oiv_id , oiv_name                            
        ');
        $stmt->execute();        
        return $stmt->fetchAll();        
    }    
}
