parameters:
    ############################################################################
    # Сообщения                                                                #
    ############################################################################
    
    ncuomap.msg.service_error: "Ошибка взаимодействия с сервером!"
    ncuomap.msg.exception: "При выполнении запроса произошла ошибка! В журнале событий сохранена запись с номером %s"

    ### Basic Auth
    ncuomap.basicauth: "devops:Q1w2e3r4"