parameters:
    ############################################################################
    # Сообщения                                                                #
    ############################################################################
    
    ncuoservice.msg.service_error: "Ошибка взаимодействия с сервером!"
    ncuoservice.msg.exception: "При выполнении запроса произошла ошибка! В журнале событий сохранена запись с номером %s"

    ### Basic Auth
    ncuoservice.basicauth: "centr_srv:Q1w2e3r4"