<?php

namespace App\NCUO\FoivBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FoivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class FoivRepository extends EntityRepository
{
    
    /**
     * Функция получения кол-ва ФОИВ
     */
    
    public function getTotalCount() {
        return $this->getEntityManager()->createQuery('SELECT COUNT(f) FROM NCUOFoivBundle:Foiv f')->getSingleScalarResult();
    }
    
    /**
     * Функция получения списка ФОИВ с кол-во дочерних ФОИВ и Инф. систем
     */
    
    public function getRoivSystemsCount() {
        $conn = $this->getEntityManager()->getConnection();
        $stmt = $conn->prepare(
        '
            select
                  f.id as foiv_id
                , f.name as foiv_name
                , (select count(*) from eif_data2.dict_roiv r where r.foiv = f.id) as cnt_roiv
                , (select count(*) from eif_data2.dict_systems s where s.foiv = f.id) as cnt_systems
            from
                eif_data2.dict_foiv f
            order by foiv_id , foiv_name                            
        ');
        $stmt->execute();        
        return $stmt->fetchAll();        
    }
    
    
}
