<?php

namespace App\NCUO\FoivBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FoivPersonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class FoivPersonsRepository extends EntityRepository
{
    
    /**
     * Функция получения списка руководства ФОИВ
     */
    
    public function getFoivDirectorsList($id_foiv) {
            $em = $this->getEntityManager();
            return $em->createQuery(
                '
                SELECT f
                FROM NCUOFoivBundle:FoivPersons f where f.fkFoiv =:id_foiv and trim(f.fio) !=\'\'
                '
            )
            ->setParameter('id_foiv', $id_foiv)
            ->getResult();
    }
	
	public function getDataFromOldFields()
	{
		$SQLText = "select fp.id as \"ID\", fp.fio as \"FIO\", fp.position as \"POS\", fp.address as \"ADDR\", ";
		$SQLText .="fp.email as \"EMAIL\", fp.phone \"PHONE\", fp.website_url as \"WURL\", fp.photo as \"PHOTO\",  ";
		$SQLText .="fp.photo_id as \"FID\", fp.photo_url as \"PURL\", fp.person_id as \"PID\" from eif_data2.dict_foiv_persons fp";
		
		$em = $this->getEntityManager();
		$connection = $em->getConnection();
		$statement = $connection->prepare($SQLText);
		$statement->execute();
		
		$results = $statement->fetchAll();
		
		return $results;
	}
}
