<?php

namespace App\NCUO\FoivBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RoivRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class RoivRepository extends EntityRepository
{
    
    /**
     * Функция получения кол-ва РОИВ
     */
    
    public function getTotalCount() {
        return $this->getEntityManager()->createQuery('SELECT COUNT(r) FROM NCUOFoivBundle:Roiv r')->getSingleScalarResult();
    }
}
