<?php

namespace App\NCUO\FoivBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SystemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class SystemsRepository extends EntityRepository
{
    
    /**
     * Функция получения кол-ва ИС
     */
    
    public function getTotalCount() {
        return $this->getEntityManager()->createQuery('SELECT COUNT(s) FROM NCUOFoivBundle:Systems s')->getSingleScalarResult();
    }
}
