parameters:
    ############################################################################
    # Системные настройки                                                      #
    ############################################################################
    
    ncuoeif.file_upload_dir: "/var/_uploaded"    
    ncuoeif.file_capi_dir_out: "/var/_capi_dir_out"
    ncuoeif.file_capi_dir_in: "/var/_capi_dir_in"

    ############################################################################
    # Сообщения                                                                #
    ############################################################################
    
    ncuoeif.msg.service_error: "Ошибка взаимодействия с сервером!"
    ncuoeif.msg.exception: "При выполнении запроса произошла ошибка! В журнале событий сохранена запись с номером %s"
